config/routes.rb
Football::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  root to: "home#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :articles
  
  resources :tv, only: [:index]
  resources :category_news, path: :category, as: :category do
    resources :articles, path: :posts
  end

  resources :articles, only: [:feed], path: :posts do
    collection do
      get :feed
    end
  end
  
  resources :clubs
  resources :players

end

app/views/shared/modules/sidebar/_articles_clubs.html.haml
.nearby-clubs.white-block.mt20
	%h3.title.dark
		.top под
		.bottom прицелом
	.clubs
		- @clubs.each do |club|
			= link_to club, class: 'club' do	
				.image= image_tag club.logo_url(:small)
				.name
					= club.title
					.city= club.city
		- @players.each do |player|
			= link_to player, class: 'club' do	
				.image= image_tag player.photos_uri[:small]
				.name
					= player.name
					.city= player.nickname

app/views/shared/modules/sidebar/_categories.html.haml
.cat.white-block.mt20.feed
	%h3.title.dark
		.top материалы 
		.bottom по категориям
	- if @categories.count > 0
		- @categories.each do |category|
			.root-category
				= link_to '#', class: 'root', data: {id: category.id} do
					= category.title
					%small.pull-right РАЗВЕРНУТЬ
					%small.pull-right.hide СВЕРНУТЬ
				.child-list(data-parent="#{category.id}")
					- category.siblings.each do |sibcat|
						= link_to sibcat.title, category_path(sibcat)
	- else
		К сожалению, похожих материалов нет :(

app/views/shared/modules/sidebar/_club_info.html.haml
.club-info-module.white-block.mt20
	%h3.title.dark
		.top= @club.title
		.bottom= @club.city

	.image.text-center= image_tag @club.logos_uri[:big]

	%table.table
		- @club.information.each do |property, value|
			- if value != ''
				%tr
					%th.text-right= I18n.t property, scope: 'club.information'
					%td= value

app/views/shared/modules/sidebar/_club_map.html.haml
%h3 Карта
.white-block.mt20
	= gmaps({"map_options" => {"auto_zoom" => false, "zoom" => 13}, "markers" => {"data" => @json}})

app/views/shared/modules/sidebar/_clubs_near.html.haml
.nearby-clubs.white-block.mt20
	%h3.title.dark
		.top соседние
		.bottom клубы
	.clubs
		- if @clubs.count > 0
			- @clubs.each do |club|
				= link_to club, class: 'club' do	
					.distance= "#{club.distance.to_i} km"
					.image= image_tag club.logo_url(:small)
					.name
						= club.title
						.city= club.city
		- else
			= "Хм.. Похоже, что '#{@club.title}' находится на необитаемом острове! Либо.. его 'соседей' еще нет в базе данных сайта ;)"

app/views/shared/modules/sidebar/_last_transfers.html.haml
.latest-transfers.white-block.mt20
	%h3.title.dark
		.top последние
		.bottom трансферы
	- if @transfers
		- @transfers.each do |transfer|
			.transfer-block
				= link_to transfer.player do
					.player
						.image= image_tag transfer.player.photos_uri[:small]
						.text-block
							.name= transfer.player.name
							.country= I18n.t transfer.player.country, scope: 'countries'
				.clubs
					.club.tipTip.tip_top{title: "#{transfer.from.title} #{transfer.from.city}"}
						= link_to transfer.from do
							= image_tag transfer.from.logos_uri[:gmaps]
					.arrow
					.club.tipTip.tip_top{title: "#{transfer.to.title} #{transfer.to.city}"}
						= link_to transfer.to do
							= image_tag transfer.to.logos_uri[:gmaps]
				.amount= "#{number_to_human transfer.amount, units: {million: 'млн.', thousand: 'тыс.'}} #{I18n.t transfer.unit, scope: 'money.names'}"
	- else
		К сожалению, трасферы не пользуются популярностью :(

app/views/shared/modules/sidebar/_matches.html.haml
.match-center-module.white-block.mt20
	%h3.title.dark
		.top текущие
		.bottom события
	- @matches.each do |key, matches|
		.competition= key
		%table
			- matches.each do |match|
				= render 'shared/tv/match', match: match, competition_title: 'false'
	- if @matches.count == 0
		На сегодня TV-трансляций пока не запланировано.

app/views/shared/modules/sidebar/_player_info.html.haml
.player-info-module.white-block.mt20
	%h3.title.dark
		.top= @player.name
		.bottom= @player.nickname

	.image.text-center
		= image_tag @player.photos_uri[:large]
		= link_to @player.club do
			.team-info
				.club= image_tag @player.club.logos_uri[:small]
				.team
					.top= @player.club.title
					.bottom= @player.club.city
				.number= @player.number

	%table.table
		%tr
			%th.text-right День рождения
			%td
				= Russian::strftime(@player.birthday, '%d %B %Y')
				%span.label.label-default= "#{@player.age} лет"
		%tr
			%th.text-right Рост
			%td= "#{@player.height} см"
		%tr
			%th.text-right Вес
			%td= "#{@player.weight} кг"
		%tr
			%th.text-right Позиция
			%td
				- @player.position.order('line ASC').each do |position|
					%span.label{class: "label-#{Position::POSITION_LABEL[position.line]}"}= position.short
		%tr
			%th.text-right Страна
			%td= I18n.t @player.country, scope: :countries
		%tr
			%th.text-right Номер
			%td= @player.number

app/views/shared/modules/sidebar/_related.html.haml
.match-center-module.white-block.mt20.feed
	%h3.title.dark
		.top материалы 
		.bottom по теме
	- if @articles.count > 0
		- @articles.each do |key, articles|
			= "#{key} назад"
			- articles.each do |article|
				= link_to category_article_path(article.category, article) do
					%article
						%b.title= article.title
						.content= article.snippet
	- else
		К сожалению, похожих материалов нет :(