config/routes.rb
Football::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  root to: "home#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :articles
  
  resources :tv, only: [:index]
  resources :category_news, path: :category, as: :category do
    resources :articles, path: :posts
  end

  resources :articles, only: [:feed], path: :posts do
    collection do
      get :feed
    end
  end
  
  resources :clubs
  resources :players

end

app/views/shared/layout/_article.html.haml
- @articles.each do |index, articles|
	.feed-day
		.col-lg-3.main-date= Russian::strftime(DateTime.parse(index), '%a, %d %B')
		.col-lg-9
			- articles.each do |article|
				%article.white-block
					.image= image_tag article.images_uri[:small]
					%h4= link_to article.title, category_article_path(article.category, article)
					.block.category
						%span.title Категория
						= "#{article.category.parent.title}.#{article.category.title}"
					- if article.tags.count > 0
						.block.tags
							%span.title Теги
							= article.tag_list
					.snippet= article.snippet

= paginate @articles_arr, left: 3, right: 3, window: 1, remote: true

app/views/shared/layout/_nav.html.haml
.navbar.green.navbar-fixed-top{ role: "navigation" }
	.container
		.navbar-header
			%button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			= link_to "FOOTBALL", root_path, class: 'navbar-brand'

		.navbar-collapse.collapse.navbar-responsive-collapse.navbar-ex1-collapse
			%ul.nav.navbar-nav.menu-link
				%li{ class: params[:controller] == 'home' && params[:action] == 'index' ? 'active' : '' }
					= link_to "Главная", root_path, data: {replace: 'true'}
				%li{ class: params[:controller] == 'tv' && params[:action] == 'index' ? 'active' : '' }
					= link_to "TV-трансляции", tv_index_path, data: {replace: 'true'}
				%li{ class: params[:controller] == 'articles' ? 'active' : '' }
					= link_to "Новости", feed_articles_path, data: {replace: 'true'}